config/routes.rb
HexagonalBlog::Application.routes.draw do
  root :to => "blog_posts#index"
  resources :blog_posts do
    resources :comments
  end
  resources :activities, :only => [:index]
  resource :author_session, :only => [:new, :create, :destroy]
  resource :settings

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :content, :type
end

app/models/author_session.rb
class AuthorSession
  include ActiveAttr::Model

  attribute :password, :type => String

  validate :has_correct_password?
  def has_correct_password?
    errors.add(:password, "invalid") unless password == AUTHOR_PASSWORD
  end
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  attr_accessible :body, :title, :published

  has_many :comments

  scope :published, where("published_at not null")

  def published
    published_at.present?
  end
  alias_method :published?, :published

  def published=(other)
    if other == true
      self.published_at = Time.zone.now
    else
      self.published_at = nil
    end
  end

  def url
    Rails.application.routes.url_helpers.blog_post_url(self)
  end

  def restricted?
    not published?
  end
end

app/models/blog_post_creation_activity.rb
class BlogPostCreationActivity < Activity
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :email, :name
  default_scope { visible }

  scope :visible, where(removed_at: nil)
  scope :removed, where("removed_at IS NOT NULL")

  belongs_to :blog_post

  def remove!
    self.removed_at = Time.zone.now
    save!
  end
end

app/models/comment_creation_activity.rb
class CommentCreationActivity < Activity
end

app/models/settings.rb
class Settings < ActiveRecord::Base
  attr_accessible :enable_comments

  def self.fetch
    first || create!
  end

  def self.comments_enabled?
    fetch.enable_comments?
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def require_author
    if not logged_in?
      flash[:error] = "Access denied"
      redirect_to root_path
    end
  end

  def logged_in?
    session[:logged_in] == true
  end

  def login!
    session[:logged_in] = true
  end

  def logout!
    session[:logged_in] = nil
  end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
    @author_session = AuthorSession.new
  end

  def create
    @author_session = AuthorSession.new(params[:author_session])
    if @author_session.valid?
      login!
      flash[:success] = "Logged in successfully"
      redirect_to root_path
    else
      flash.now[:error] = "Invalid credentials"
      render :new
    end
  end

  def destroy
    logout!
    redirect_to root_path
  end
end

app/controllers/blog_posts_controller.rb
require 'twitter'
require 'blog_post_librarian'
require 'blog_post_creator'
require 'blog_post_updater'
require 'blog_post_finder'
require 'activity_logger'
require 'blog_tweeter'

class BlogPostsController < ApplicationController
  before_filter :require_author, :except => [:index, :show]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    blog_post_librarian = BlogPostLibrarian.new(self)
    blog_post_librarian.find(params, logged_in?)
  end

  def blog_posts_found(posts)
    @blog_posts = posts
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blog_posts }
    end
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    blog_post_finder = BlogPostFinder.new(self)
    blog_post_finder.find(:with => params, :author? => logged_in?)
  end

  def blog_post_found(blog_post)
    @blog_post = blog_post
    @comments = @blog_post.comments

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog_post }
    end
  end

  def blog_post_not_found
    flash[:notice] = "Blog post not found"
    redirect_to root_path
  end

  def blog_post_restricted
    # From reader perspective, restricted is the same as missing
    blog_post_not_found
  end

  # GET /blog_posts/new
  # GET /blog_posts/new.json
  def new
    @blog_post = BlogPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog_post }
    end
  end

  # GET /blog_posts/1/edit
  def edit
    @blog_post = BlogPost.find(params[:id])
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    blog_post_creator = BlogPostCreator.new(ActivityLogger.new(BlogTweeter.new(self)))
    blog_post_creator.create_with(params[:blog_post])
  end

  # The creator will call these VV, depending on what happened with blog post creation
  def blog_post_creation_succeeded(blog_post)
    @blog_post = blog_post
    respond_to do |format|
      format.html { redirect_to edit_blog_post_path(@blog_post), notice: 'The blog post was successfully created.' }
      format.json { render json: @blog_post, status: :created, location: @blog_post }
    end
  end

  def blog_post_creation_failed(blog_post)
    @blog_post = blog_post
    respond_to do |format|
      format.html { render action: "new" }
      format.json { render json: @blog_post.errors, status: :unprocessable_entity }
    end
  end

  # PUT /blog_posts/1
  # PUT /blog_posts/1.json
  def update
    blog_post_updater = BlogPostUpdater.new(self)
    blog_post_updater.update(params)
  end

  def blog_post_update_succeeded(blog_post)
    @blog_post = blog_post
    respond_to do |format|
      format.html { redirect_to @blog_post, notice: 'The blog post was successfully updated.' }
      format.json { head :no_content }
    end
  end

  def blog_post_update_failed(blog_post)
    @blog_post = blog_post
    respond_to do |format|
      format.html { render action: "edit" }
      format.json { render json: @blog_post.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post = BlogPost.find(params[:id])
    @blog_post.destroy

    respond_to do |format|
      format.html do
        flash[:success] = "Blog post successfully removed."
        redirect_to blog_posts_url, :success => "Blog post successfully removed."
      end
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
require 'comment_creator'
class CommentsController < ApplicationController

  def create
    comment_creator = CommentCreator.new(ActivityLogger.new(self))
    comment_creator.create_with(params[:blog_post_id], params[:comment])
  end

  def comment_creation_succeeded(comment)
    redirect_to comment.blog_post
  end

  def comment_creation_failed(comment)
    # not sure what happens here, no failure has pointed for me what to do
  end

  def destroy
    @blog_post = BlogPost.find(params[:blog_post_id])
    @comment = @blog_post.comments.find(params[:id])
    @comment.remove!

    redirect_to @blog_post
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def edit
    @settings = Settings.fetch
  end

  def update
    @settings = Settings.fetch
    @settings.update_attributes(params[:settings])
    flash[:success] = "Settings saved"
    redirect_to edit_settings_path
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def activity_string(activity)
    string = ""
    string << activity.created_at.to_s
    string << ": "
    string << activity.content
    return string
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/activities/_activity.html.erb
<article class="activity">
  <%= activity_string(activity) %>
</article>

app/views/activities/index.html.erb
<%= render @activities.map { |activity| activity.becomes(Activity) } %>

app/views/author_sessions/new.html.erb
<%= form_for @author_session, :url => author_session_path do |f| %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit "Login" %>
<% end %>

app/views/blog_posts/_blog_post.html.erb
<article class="blog_post">
  <header>
    <h1><%= blog_post.title %></h1>
    <time><%= blog_post.created_at %></time>
  </header>
  <%= blog_post.body.html_safe %>
</article>

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing blog_post</h1>

<%= render 'form' %>

<%= render @blog_post %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<h1>Listing blog_posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blog_posts.each do |blog_post| %>
  <tr>
    <td><%= blog_post.title %></td>
    <td><%= blog_post.body %></td>
    <td><%= link_to 'Show', blog_post %></td>
    <td><%= link_to 'Edit', edit_blog_post_path(blog_post) %></td>
    <td><%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog post', new_blog_post_path %>

app/views/blog_posts/new.html.erb
<h1>New blog_post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @blog_post %>

<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>

<% if Settings.comments_enabled? %>
  <%= render @comments %>
  <%= render 'comments/form' %>
<% end %>

app/views/comments/_comment.html.erb
<article class="comment">
  <%= comment.name %>
  <%= comment.body %>
  <%= link_to "Remove", [comment.blog_post, comment], :method => :delete %>
</article>

app/views/comments/_form.html.erb
<%= form_for [@blog_post, @blog_post.comments.build] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :body, "Comment" %>
  <%= f.text_area :body %>

  <%= f.submit "Submit" %>
<% end %>

app/views/layouts/_notice.html.erb
<% if flash.any? %>
  <% flash.each do |type, message| %>
    <p class='flash <%= type %>'>
      <%= message %>
    </p>
  <% end %>
<% end %>
<%%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HexagonalBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/notice' %>

<%= yield %>

</body>
</html>

app/views/settings/edit.html.erb
<%= form_for @settings, :url => settings_path do |f| %>
  <%= f.label :enable_comments %>
  <%= f.check_box :enable_comments %>

  <%= f.submit "Save Settings" %>
<% end %>